"""FIFA futsal pitch geometry: constants, keypoints, goal polygons, utilities."""

from .pitch import (
    ARC_FOOT_Y1,
    ARC_FOOT_Y2,
    CENTER_CIRCLE_RADIUS_M,
    GOAL_DEPTH_M,
    GOAL_HEIGHT_M,
    GOAL_POST_Y1,
    GOAL_POST_Y2,
    GOAL_WIDTH_M,
    HALF_LENGTH,
    HALF_WIDTH,
    KEEPER_ARC_RADIUS_M,
    KEYPOINT_NAMES,
    KEYPOINTS,
    LEFT_GOAL_POLYGON,
    NUM_KEYPOINTS,
    PENALTY_SPOT_1_M,
    PENALTY_SPOT_2_M,
    PITCH_LENGTH_M,
    PITCH_WIDTH_M,
    RIGHT_GOAL_POLYGON,
    SUBSTITUTION_ZONE_HALF_LENGTH_M,
    center_circle_points,
    keeper_arc_points,
    point_in_polygon,
)

__all__ = [
    "PITCH_LENGTH_M",
    "PITCH_WIDTH_M",
    "GOAL_WIDTH_M",
    "GOAL_DEPTH_M",
    "GOAL_HEIGHT_M",
    "PENALTY_SPOT_1_M",
    "PENALTY_SPOT_2_M",
    "KEEPER_ARC_RADIUS_M",
    "CENTER_CIRCLE_RADIUS_M",
    "SUBSTITUTION_ZONE_HALF_LENGTH_M",
    "HALF_LENGTH",
    "HALF_WIDTH",
    "GOAL_POST_Y1",
    "GOAL_POST_Y2",
    "ARC_FOOT_Y1",
    "ARC_FOOT_Y2",
    "KEYPOINTS",
    "KEYPOINT_NAMES",
    "NUM_KEYPOINTS",
    "LEFT_GOAL_POLYGON",
    "RIGHT_GOAL_POLYGON",
    "keeper_arc_points",
    "center_circle_points",
    "point_in_polygon",
]
