[theme]
base = "dark"
primaryColor = "#d85c7d"
backgroundColor = "#0e0e12"
secondaryBackgroundColor = "#17171f"
textColor = "#d4d4d8"
font = "sans serif"

[server]
headless = true
runOnSave = true
address = "0.0.0.0"
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
